os: osx
osx_image: xcode9.3

language: node_js
node_js: 8

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn test
  - yarn archive

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: dist/*
  skip_cleanup: true

branches:
  only:
    - master
